using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum Scenes {
    MAINMENU,
    MODESELECTION,
    NORMALLEVELSELECTION,
    ENDLESSLEVELSELECTION,
    OPTIONS,
    SHOP,
    DEATH,
    NORMAL_FOREST_1,
    NORMAL_FOREST_2,
    NORMAL_FOREST_3,
    NORMAL_GAMEBOY_1,
    NORMAL_GAMEBOY_2,
    NORMAL_GAMEBOY_3,
    NORMAL_CASTLE_1,
    NORMAL_CASTLE_2,
    NORMAL_CASTLE_3,
    NORMAL_TOWN_1,
    NORMAL_TOWN_2,
    NORMAL_TOWN_3,
    ENDLESS_FOREST_1,
    ENDLESS_FOREST_2,
    ENDLESS_FOREST_3,
    ENDLESS_GAMEBOY_1,
    ENDLESS_GAMEBOY_2,
    ENDLESS_GAMEBOY_3,
    ENDLESS_CASTLE_1,
    ENDLESS_CASTLE_2,
    ENDLESS_CASTLE_3,
    ENDLESS_TOWN_1,
    ENDLESS_TOWN_2,
    ENDLESS_TOWN_3
}
